### ISSUE TITLE
Option to add maximums and minimums in the next few days

### ISSUE THREAD

**Issue by javiavid** [ms3056/Tenki#2]
It is possible to add an option to activate the maximum and minimum temperatures in the following days?
Thanks

**Comment by kmaustral** [comment]
I was about to leave the same request.

**Comment by ms3056** [comment]
This is already implemented. Hover your cursor over each day.

**Comment by ms3056** [comment]
![image](https://github.com/ms3056/Tenki/assets/23712700/ab441445-4d1c-4ca5-a7bf-5dc88cff64df)

**Comment by kmaustral** [comment]
That's good to know, thank you. It would be nice to be able to customise this, like to show the maximum temperature with rainfall as a hover. And maybe combine this with Tokei so it can show weather from other places as well.

**Comment by ms3056** [comment]
The percentage is the percent rainfall for that day. There is some information about rainfall in the free weather feed - but I honestly found it not that accurate. 

Displaying weather from multiple locations is out of scope. 

I will keep this app separate from Tokei. 

Thanks for using the app. As this is the first public release I will plan future upgrades based on user feedback, but the real purpose of the plugin is just a quick, simple weather display. 

Please note: all of the information displayed has specific CSS classes - you can use a CSS snippet to change just about anything you want - someone on the Discord has even posted some screenshots of changing the icons.
