### ISSUE TITLE
Empty panel

### ISSUE THREAD

**Issue by javiavid** [ms3056/Tenki#3]
The empty panel appears.
I have tried with:
Madrid
Madrid, Spain

I have also tried closing and opening Obsidian and clicking refresh in the command palette

<img width="948" alt="image" src="https://github.com/ms3056/Tenki/assets/7627504/35651450-38dc-4e36-be2a-39c40601f5d7">

<img width="324" alt="image" src="https://github.com/ms3056/Tenki/assets/7627504/e3e48a7b-0a99-4f33-b834-d68f732a9f60">

SYSTEM INFO:
	Obsidian version: v1.4.12
	Installer version: v1.4.5
	Operating system: Windows 10 Pro 10.0.22621
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: none
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 34
	Plugins enabled: 2
		1: Obsidian42 - BRAT v0.7.0
		2: Tenki v0.7.6

**Comment by ms3056** [comment]
Hi - I have tested Madrid and Madrid, Spain and both work for me. 

Can you try another city? Try Tokyo. 

I suspect you have entered your api key incorrectly. You can test it in this website: https://www.weatherapi.com/api-explorer.aspx

If you get no response, then it is for sure your API key entry.  If you are positive your API is correct, and the website above comes back empty - then your network is blocking the connection to the website. 


![image](https://github.com/ms3056/Tenki/assets/23712700/d05a3d2a-3526-49b0-ba25-0fc813b589de)

**Comment by ms3056** [comment]
Also - don't update every 0.5 minutes - the web feed updates every 15 minutes - there is no need to update so often.

**Comment by ms3056** [comment]
Closed - can not duplicate. Check API Key and check api tester link in my reply.

**Comment by javiavid** [comment]
Fixed, the API was not copied correctly.
Thank you

**Comment by ms3056** [comment]
Excellent - thank you for using the plugin!
